build website:
  stage: build
  cache:
    paths:
      - node_modules/
  image: node:19
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

deploy to s3:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp public s3://$S3_BUCKET --recursive